on:
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build My Profile Page
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code   # 第一步：拉取代码
      uses: actions/checkout@v4

    
    - name: Setup Python
      uses: actions/setup-python@v6.0.0
      with:
        python-version: 3.10.9
    
    - name: Install Req
      run: |
       python -m pip install -r 'requirements.txt'
       python build_static.py

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: index.html
        path: /
